(function(){
'use strict';
const $=id=>document.getElementById(id),esc=escapeHtml,api=()=>window.CAGE_BACKEND;
const localDay=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
function addDays(day,n){const d=new Date(day+'T12:00:00');d.setDate(d.getDate()+n);return localDay(d);}
function weekStart(day){const d=new Date(day+'T12:00:00');return addDays(day,-((d.getDay()+6)%7));}
function group(plan,day){if(!plan||plan.bucket==='backlog')return 'backlog';if(plan.bucket==='day')return plan.plan_date===day?'day':plan.plan_date<day?'backlog':'later';if(plan.bucket==='week')return weekStart(plan.plan_date)===weekStart(day)?'week':plan.plan_date<weekStart(day)?'backlog':'later';return 'later';}
let data={plans:[],capacity:480,users:[]},ownPlans=[],selectedUser='',day=localDay(),loading=false,requestNumber=0,filter='',dragged='',lastLoad=0;
const profile=()=>api().currentProfile(),isOwn=()=>selectedUser===profile()?.id,canEdit=()=>isOwn()&&api().moduleLevel('tasks')==='edit';
const person=()=>data.users.find(u=>u.id===selectedUser)||profile();
const memberId=()=>{const id=person()?.email?.split('@')[0];return id==='bonfancio'?'bonifancio':id;};
const assigned=()=>state.tasks.filter(t=>t.owner===memberId());
const planFor=id=>data.plans.find(p=>p.task_id===id);
function taskPlan(id){return {...{task_id:id,bucket:'backlog',plan_date:null,estimate_minutes:60,start_at:null,end_at:null,time_zone:Intl.DateTimeFormat().resolvedOptions().timeZone},...planFor(id)};}
const time=iso=>iso?new Date(iso).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'';
const host=document.createElement('article');host.id='daily-planner';host.className='surface';host.innerHTML=`<div class="planner-heading"><div><p class="section-kicker">Daily plan</p><h3>Plan your workday</h3><p>Move tasks into a realistic plan without changing project deadlines.</p></div><div class="planner-tools"><button id="planner-add" type="button">＋ Add task</button><button id="planner-review" type="button">Review my day</button></div></div><div class="planner-toolbar"><label>Plan for<input id="planner-day" type="date"></label><button type="button" id="planner-today">Today</button><label id="planner-person-label" hidden>Staff plan<select id="planner-person"></select></label><label>Capacity<input id="planner-capacity" type="number" min="0.5" max="24" step="0.5" value="8"><span>hours</span></label><button type="button" id="planner-save-capacity">Save</button><label class="planner-search">Find a task<input id="planner-search" type="search" placeholder="Search task or project"></label></div><p id="planner-status" role="status"></p><div id="planner-summary"></div><div id="planner-board" class="planner-board"></div><div class="planner-time-heading"><div><p class="section-kicker">Schedule</p><h3>Time blocks</h3></div></div><div id="planner-timeline"></div>`;
document.getElementById('mywork-planner-slot').append(host);
$('planner-day').value=day;
document.body.insertAdjacentHTML('beforeend',`<dialog class="app-dialog" id="task-plan-dialog"><form id="task-plan-form"><div class="dialog-heading"><h2>Plan task</h2><button type="button" data-plan-close="task-plan-dialog">×</button></div><input name="taskId" type="hidden"><p id="task-plan-title"></p><label class="field"><span>Planning column</span><select name="bucket"><option value="backlog">My backlog</option><option value="day">Selected day</option><option value="week">This week</option><option value="later">Later</option></select></label><label class="field"><span>Planning date</span><input name="date" type="date" required></label><label class="field"><span>Estimated minutes</span><input name="estimate" type="number" min="5" max="10080" required step="5"></label><p>Optional time block (your device's time zone)</p><div class="form-grid"><label class="field"><span>Start</span><input name="start" type="time"></label><label class="field"><span>End</span><input name="end" type="time"></label></div><p id="task-plan-error" role="alert"></p><div class="dialog-actions"><button type="button" data-plan-close="task-plan-dialog">Cancel</button><button class="primary-button">Save plan</button></div></form></dialog><dialog class="app-dialog" id="planner-status-dialog"><form id="planner-status-form"><div class="dialog-heading"><h2>Update original task</h2><button type="button" data-plan-close="planner-status-dialog">×</button></div><input name="taskId" type="hidden"><p id="planner-task-title"></p><label class="field"><span>Status</span><select name="status"><option>To Do</option><option>In Progress</option><option>Blocked</option><option>Done</option></select></label><label class="field"><span>Priority</span><select name="priority"><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></label><label class="field"><span>Blocker reason (required when blocked)</span><textarea name="blocker"></textarea></label><label class="field"><span>Completion evidence or note</span><textarea name="evidence"></textarea></label><p id="planner-update-error" role="alert"></p><div class="dialog-actions"><button type="button" data-plan-close="planner-status-dialog">Cancel</button><button class="primary-button">Update task</button></div></form></dialog><dialog class="app-dialog" id="planner-review-dialog"><h2>Review your day</h2><p id="planner-review-copy"></p><div id="planner-review-list"></div><button type="button" data-plan-close="planner-review-dialog">Close review</button></dialog>`);
async function load(){if(!profile())return;selectedUser||=profile().id;const current=++requestNumber;loading=true;try{const result=await api().plannerData(selectedUser);if(current!==requestNumber)return;data=result;if(isOwn())ownPlans=data.plans;lastLoad=Date.now();$('planner-status').textContent='';populatePeople();render();if(activeView==='calendar')renderCalendar();}catch(e){if(current===requestNumber)$('planner-status').textContent='Could not load the planner. '+e.message;}finally{if(current===requestNumber)loading=false;}}
function populatePeople(){const manager=['admin','manager'].includes(profile()?.role);$('planner-person-label').hidden=!manager;$('planner-person').innerHTML=data.users.filter(u=>manager||u.id===profile().id).map(u=>`<option value="${u.id}" ${u.id===selectedUser?'selected':''}>${esc(u.full_name)}</option>`).join('');$('planner-capacity').value=data.capacity/60;$('planner-capacity').disabled=!canEdit();$('planner-save-capacity').hidden=!canEdit();$('planner-add').hidden=!canEdit();$('planner-review').hidden=!canEdit();}
function render(){if(!profile())return;if(api().moduleLevel('tasks')==='none'){host.hidden=true;return;}host.hidden=false;const all=assigned(),matches=all.filter(t=>(t.title+' '+(projectById(t.project)?.name||'')).toLowerCase().includes(filter));const today=all.filter(t=>{const p=planFor(t.id);return p?.bucket==='day'&&p.plan_date===day;});const total=today.reduce((sum,t)=>sum+(planFor(t.id)?.estimate_minutes||60),0),complete=today.filter(t=>t.status==='Done').length;
const away=window.CAGE_OPS?.onLeave(memberId(),day);const capacity=away?0:data.capacity;
$('planner-summary').innerHTML=`<div class="planner-progress-copy"><strong>${complete} of ${today.length} completed</strong><span>${+(total/60).toFixed(1)}h planned · ${capacity/60}h capacity</span></div><div class="planner-progress"><span style="width:${today.length?Math.round(complete/today.length*100):0}%"></span></div><p>${away?'Approved leave: capacity is zero. Move planned work to another day.':total>capacity?'This day is over capacity. Move a task or adjust an estimate.':'Your plan has room for focused work and the unexpected.'}${!isOwn()?' You are reviewing this staff member’s plan.':''}</p>`;
$('planner-board').innerHTML=[['backlog','My backlog'],['day',day===localDay()?'Today':day],['week','This week'],['later','Later']].map(([key,label])=>{const tasks=matches.filter(t=>group(planFor(t.id),day)===key&&(t.status!=='Done'||key==='day'));return `<section data-plan-drop="${key}"><h4>${label} <span>${tasks.length}</span></h4>${tasks.map(t=>{const p=planFor(t.id);return `<article class="planner-task" draggable="${canEdit()}" data-plan-task="${esc(t.id)}"><button type="button" class="planner-task-title" data-planner-open="${esc(t.id)}">${esc(t.title)}</button><small>${esc(projectById(t.project)?.name||'Unlinked')} · Deadline: ${esc(t.due||'Not set')}</small><div class="planner-tags"><span>${esc(t.status)}</span><span>${esc(t.priority||'Medium')}</span><span>${p?p.estimate_minutes+' min':'Estimate not set'}</span></div>${p?.plan_date&&p.plan_date!==day?`<small>Planned: ${esc(p.plan_date)}</small>`:''}${p?.start_at?`<small>${time(p.start_at)}–${time(p.end_at)}</small>`:''}<div class="planner-card-actions"><button type="button" data-edit-plan="${esc(t.id)}" ${canEdit()?'':'disabled'}>Plan / time block</button><button type="button" data-plan-status="${esc(t.id)}" ${canEdit()?'':'disabled'}>Status / priority</button></div><button type="button" data-plan-title="${esc(t.title)}" ${canEdit()?'':'disabled'}>Remind me</button><label class="planner-move-label">Move to<select data-plan-move="${esc(t.id)}" ${canEdit()?'':'disabled'}>${[['backlog','Backlog'],['day','Selected day'],['week','This week'],['later','Later']].map(([v,n])=>`<option value="${v}" ${v===key?'selected':''}>${n}</option>`).join('')}</select></label></article>`;}).join('')||'<p class="planner-empty">No tasks here.</p>'}</section>`;}).join('');
$('planner-timeline').innerHTML=today.filter(t=>planFor(t.id)?.start_at).sort((a,b)=>planFor(a.id).start_at.localeCompare(planFor(b.id).start_at)).map(t=>`<button type="button" class="planner-time-block" data-planner-open="${esc(t.id)}"><strong>${time(planFor(t.id).start_at)}–${time(planFor(t.id).end_at)}</strong><span>${esc(t.title)}</span></button>`).join('')||'<p>No time blocks for this day. Use “Plan / time block” to reserve time.</p>';
}
async function move(id,bucket,date=day){if(!canEdit())return;try{await api().saveTaskPlan({...taskPlan(id),bucket,plan_date:['day','week'].includes(bucket)?date:null,start_at:null,end_at:null});await load();}catch(e){$('planner-status').textContent=e.message;render();}}
function openPlan(id){if(!canEdit())return;const task=assigned().find(t=>t.id===id);if(!task)return;const p=taskPlan(id),f=$('task-plan-form');f.reset();f.elements.taskId.value=id;f.elements.bucket.value=p.bucket;f.elements.date.value=p.plan_date||day;f.elements.estimate.value=p.estimate_minutes;f.elements.start.value=p.start_at?new Date(p.start_at).toTimeString().slice(0,5):'';f.elements.end.value=p.end_at?new Date(p.end_at).toTimeString().slice(0,5):'';$('task-plan-title').textContent=task.title;$('task-plan-error').textContent='';$('task-plan-dialog').showModal();}
function openStatus(id,status){if(!canEdit())return;const t=assigned().find(t=>t.id===id);if(!t)return;const f=$('planner-status-form');f.elements.taskId.value=id;f.elements.status.value=status||t.status;f.elements.priority.value=t.priority||'Medium';f.elements.blocker.value=t.blocker||'';f.elements.evidence.value=t.evidence||'';$('planner-task-title').textContent=t.title;$('planner-update-error').textContent='';$('planner-status-dialog').showModal();}
function review(){const list=assigned().filter(t=>{const p=planFor(t.id);return p?.bucket==='day'&&p.plan_date===day&&t.status!=='Done';});$('planner-review-copy').textContent=`${day}: ${list.length} unfinished tasks. Recognise what you achieved, then choose a realistic next step.`;$('planner-review-list').innerHTML=list.map(t=>`<div class="planner-review-row"><strong>${esc(t.title)}</strong><div><button data-review-done="${esc(t.id)}">Complete</button><button data-review-tomorrow="${esc(t.id)}">Next day</button><button data-review-later="${esc(t.id)}">Later</button></div></div>`).join('')||'<p>All planned tasks for this day are complete.</p>';if(!$('planner-review-dialog').open)$('planner-review-dialog').showModal();}
$('planner-day').onchange=e=>{if(e.target.value){day=e.target.value;render();}};$('planner-today').onclick=()=>{day=localDay();$('planner-day').value=day;render();};$('planner-person').onchange=e=>{selectedUser=e.target.value;load();};$('planner-search').oninput=e=>{filter=e.target.value.trim().toLowerCase();render();};$('planner-review').onclick=review;$('planner-add').onclick=()=>{openTaskDialog();$('task-form').elements.owner.value=api().currentMemberId();};
$('planner-save-capacity').onclick=async()=>{try{if(!canEdit())return;await api().savePlanningCapacity(Math.round(Number($('planner-capacity').value)*60));await load();}catch(e){$('planner-status').textContent=e.message;}};
$('task-plan-form').onsubmit=async e=>{e.preventDefault();if(!canEdit())return;const f=e.currentTarget,b=e.submitter;b.disabled=true;try{const bucket=f.elements.bucket.value,start=f.elements.start.value,end=f.elements.end.value;if(Boolean(start)!==Boolean(end))throw new Error('Set both the start and end time, or leave both blank.');if(start&&bucket!=='day')throw new Error('Choose Selected day to reserve a time block.');if(start&&end<=start)throw new Error('End time must be after start time on the same day.');await api().saveTaskPlan({task_id:f.elements.taskId.value,bucket,plan_date:['day','week'].includes(bucket)?f.elements.date.value:null,estimate_minutes:Number(f.elements.estimate.value),start_at:start?new Date(f.elements.date.value+'T'+start).toISOString():null,end_at:end?new Date(f.elements.date.value+'T'+end).toISOString():null,time_zone:Intl.DateTimeFormat().resolvedOptions().timeZone});$('task-plan-dialog').close();await load();}catch(e){$('task-plan-error').textContent=e.message;}finally{b.disabled=false;}};
$('planner-status-form').onsubmit=async e=>{e.preventDefault();if(!canEdit())return;const f=e.currentTarget,b=e.submitter;b.disabled=true;try{await api().updatePlannedTask({task_key:f.elements.taskId.value,next_status:f.elements.status.value,next_priority:f.elements.priority.value,blocker_note:f.elements.blocker.value.trim(),completion_evidence:f.elements.evidence.value.trim()});$('planner-status-dialog').close();await load();}catch(e){$('planner-update-error').textContent=e.message;}finally{b.disabled=false;}};
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.planClose)$(b.dataset.planClose).close();if(b.dataset.plannerOpen)openTask(b.dataset.plannerOpen);if(b.dataset.editPlan)openPlan(b.dataset.editPlan);if(b.dataset.planStatus)openStatus(b.dataset.planStatus);if(b.dataset.reviewDone){$('planner-review-dialog').close();openStatus(b.dataset.reviewDone,'Done');}if(b.dataset.reviewTomorrow){await move(b.dataset.reviewTomorrow,'day',addDays(day,1));review();}if(b.dataset.reviewLater){await move(b.dataset.reviewLater,'later');review();}});
$('planner-board').addEventListener('change',e=>{if(e.target.dataset.planMove)move(e.target.dataset.planMove,e.target.value);});
$('planner-board').addEventListener('dragstart',e=>{const card=e.target.closest('[data-plan-task]');if(!card||!canEdit())return;dragged=card.dataset.planTask;e.dataTransfer.setData('text/plain',dragged);});
$('planner-board').addEventListener('dragover',e=>{if(dragged&&e.target.closest('[data-plan-drop]'))e.preventDefault();});
$('planner-board').addEventListener('drop',e=>{const col=e.target.closest('[data-plan-drop]');if(!col||!dragged)return;e.preventDefault();const id=dragged;dragged='';move(id,col.dataset.planDrop);});$('planner-board').addEventListener('dragend',()=>{dragged='';});
const originalRefresh=window.CAGE_PERSONAL.refreshView;window.CAGE_PERSONAL.refreshView=function(){originalRefresh();if(activeView==='mywork')render();};
const originalView=window.CAGE_PERSONAL.view;window.CAGE_PERSONAL.view=function(v){originalView(v);if(['mywork','calendar'].includes(v)&&Date.now()-lastLoad>10000&&!loading)load();};
const calendar=window.calendarItemsForDate;window.calendarItemsForDate=function(date){const items=calendar(date);if(api().moduleLevel('tasks')==='none')return items;const blocks=ownPlans.filter(p=>p.start_at&&localDay(new Date(p.start_at))===date).map(p=>{const t=state.tasks.find(t=>t.id===p.task_id&&t.owner===api().currentMemberId());return t?{kind:'meeting',title:'My plan: '+t.title,time:time(p.start_at),sort:new Date(p.start_at).toTimeString().slice(0,5),detail:time(p.start_at)+'–'+time(p.end_at)+' · Personal time block'}:null;}).filter(Boolean);return [...items,...blocks].sort((a,b)=>a.sort.localeCompare(b.sort));};
window.addEventListener('cage:session-ready',()=>{selectedUser=profile().id;load();});setInterval(()=>{if(!document.hidden&&['mywork','calendar'].includes(activeView)&&!loading)load();},30000);
window.CAGE_PLANNER={group,addDays,weekStart};
})();
