// Weekly totals are delivered only to an active admin rechecked immediately before sending.
export async function dispatchPresenceReports(db:any,key:string,from:string){
 const checked=async(q:any)=>{const r=await q;if(r.error)throw r.error;return r.data;};
 const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
 const duration=(n:number)=>{const seconds=Math.max(0,Math.floor(Number(n)||0));return `${Math.floor(seconds/3600)}h ${String(Math.floor(seconds/60)%60).padStart(2,'0')}m ${String(seconds%60).padStart(2,'0')}s`;};
 const jobs=await checked(db.rpc('claim_presence_reports'));let sent=0,retrying=0;
 for(let i=0;i<jobs.length;i+=5)await Promise.all(jobs.slice(i,i+5).map(async(claim:any)=>{try{
  const job=await checked(db.rpc('prepare_presence_report',{jid:claim.id}));if(!job)return;let payload=job.payload;
  if(!payload){const report=job.report;payload={from,to:[job.recipient],subject:`CAGE weekly online summary: ${report.week_start} – ${report.week_end}`,html:`<div style="font-family:Arial,sans-serif;color:#203247"><h1>Weekly active Hub time</h1><p>${esc(report.week_start)} – ${esc(report.week_end)} · Malawi time (CAT)</p><p>Administrator-only summary. Estimated active Hub time, not attendance or productivity. Away/background time is excluded. Multiple tabs and devices are counted once. Unexpected disconnects may add up to 90 seconds.</p><p>Tracking began ${esc(new Date(report.tracking_started_at).toLocaleString('en-GB',{timeZone:'Africa/Blantyre'}))} CAT. Earlier dates are untracked; the first week may be partial. Daily durations are shown to whole seconds; the displayed weekly total adds those daily figures.</p><table cellpadding="8" cellspacing="0" border="1" style="border-collapse:collapse;border-color:#dbe4eb;font-size:13px"><thead><tr><th>Member</th>${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<th>${d}</th>`).join('')}<th>Weekly total</th></tr></thead><tbody>${report.members.map((m:any)=>`<tr><td>${esc(m.name)}</td>${m.days.map((d:any)=>`<td>${duration(d.seconds)}</td>`).join('')}<td><strong>${duration(m.days.reduce((total:number,d:any)=>total+Math.floor(Number(d.seconds)||0),0))}</strong></td></tr>`).join('')}</tbody></table><p>CAGE Operations Hub</p></div>`};await checked(db.from('hub_presence_reports').update({payload}).eq('id',job.id).eq('status','processing'));}
  // Recheck role and recipient after freezing a request; retain identical payload on retries.
  if(!await checked(db.rpc('prepare_presence_report',{jid:job.id})))return;
  const r=await fetch('https://api.resend.com/emails',{method:'POST',signal:AbortSignal.timeout(15000),headers:{Authorization:'Bearer '+key,'Content-Type':'application/json','Idempotency-Key':'cage-presence-week-'+job.id},body:JSON.stringify(payload)});
  if(!r.ok)throw Error('Email provider returned '+r.status);const result=await r.json();if(!result.id)throw Error('Provider returned no confirmation');
  await checked(db.from('hub_presence_reports').update({status:'sent',sent_at:new Date().toISOString(),provider_id:result.id,error:null}).eq('id',job.id).eq('status','processing'));sent++;
 }catch(e){await checked(db.from('hub_presence_reports').update({status:'pending',error:e instanceof Error?e.message:'Report failed',available_at:new Date(Date.now()+300000).toISOString()}).eq('id',claim.id).eq('status','processing'));retrying++;}}));return {sent,retrying};
}
