import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
Deno.serve(async req=>{
 const origin=Deno.env.get('APP_URL')||'https://hub.cagemw.com';const headers={'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Content-Type':'application/json'};const reply=(v:any,status=200)=>new Response(JSON.stringify(v),{status,headers});if(req.method==='OPTIONS')return new Response('ok',{headers});if(req.method!=='POST')return reply({error:'POST required'},405);
 const url=Deno.env.get('SUPABASE_URL')!,client=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:req.headers.get('Authorization')||''}}}),admin=createClient(url,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
 const {data:auth,error}=await client.auth.getUser();if(error||!auth.user)return reply({error:'Sign in required'},401);
 const payload=await req.json().catch(()=>({}));if(!payload.cohortId||!Array.isArray(payload.learnerIds)||!payload.learnerIds.length||payload.learnerIds.length>100||typeof payload.body!=='string'||!payload.body.trim()||payload.body.length>15000||!/^[a-zA-Z0-9-]{10,64}$/.test(payload.requestId||''))return reply({error:'Choose recipients and enter a message'},400);
 const access=await client.rpc('can_cohort',{cid:payload.cohortId}),edit=await client.rpc('module_level',{m:'training'});if(!access.data||edit.data!=='edit')return reply({error:'Cohort edit access required'},403);
 const {data:p}=await client.from('profiles').select('organization_id,full_name,active').eq('id',auth.user.id).single();if(!p?.active)return reply({error:'Inactive account'},403);
 const cohort=await client.from('training_cohorts').select('name').eq('id',payload.cohortId).single();const learners=await client.from('learners').select('id,full_name,email').eq('cohort_id',payload.cohortId).in('id',[...new Set(payload.learnerIds)]);if(learners.error||learners.data?.length!==new Set(payload.learnerIds).size||learners.data.some(l=>!l.email))return reply({error:'One or more recipients are unavailable or have no email address'},400);
 const key=Deno.env.get('RESEND_API_KEY'),from=Deno.env.get('EMAIL_FROM');if(!key||!from)return reply({error:'Email sending is not configured'},503);
 const failed:string[]=[],sent:string[]=[];
 for(const l of learners.data){const input=JSON.stringify([payload.requestId,l.id,payload.body]);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(input)))).map(x=>x.toString(16).padStart(2,'0')).join('');
 const previous=await admin.from('cohort_deliveries').select('status,created_at').eq('delivery_key',hash).maybeSingle();if(previous.data?.status==='sent'){sent.push(l.id);continue;}if(previous.data&&Date.parse(previous.data.created_at)<Date.now()-23*3600000){failed.push(l.id);continue;}await admin.from('cohort_deliveries').upsert({delivery_key:hash,organization_id:p.organization_id,cohort_id:payload.cohortId,learner_id:l.id,sender_id:auth.user.id,status:'processing'});
 try{const res=await fetch('https://api.resend.com/emails',{method:'POST',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','Idempotency-Key':'cohort-'+hash},body:JSON.stringify({from,to:[l.email],subject:`CAGE ${cohort.data?.name||'Training'} — cohort update`,html:`<div style="font-family:Arial;color:#181b34"><h2>CAGE Training</h2><p>Hello ${esc(l.full_name.split(' ')[0])},</p><p style="white-space:pre-wrap">${esc(payload.body)}</p><p>${esc(p.full_name)}<br>CAGE Training Team</p></div>`})});if(!res.ok)throw new Error('Provider rejected email');sent.push(l.id);await admin.from('cohort_deliveries').upsert({delivery_key:hash,organization_id:p.organization_id,cohort_id:payload.cohortId,learner_id:l.id,sender_id:auth.user.id,status:'sent'});}
 catch{failed.push(l.id);await admin.from('cohort_deliveries').upsert({delivery_key:hash,organization_id:p.organization_id,cohort_id:payload.cohortId,learner_id:l.id,sender_id:auth.user.id,status:'failed'});}
 }
 return reply({ok:true,sent,failed});
});
