// Deterministic discovery and evidence extraction. No eligibility claims are inferred as facts.
export const SOURCES=[
 {id:'malawi',name:'Malawi procurement',domains:['ppda.mw','maneps.mw'],url:'https://www.ppda.mw/tenders',official:true},
 {id:'un',name:'UN procurement',domains:['ungm.org','procurement-notices.undp.org','unops.org'],url:'https://www.ungm.org/Public/Notice',official:true},
 {id:'banks',name:'Development banks',domains:['afdb.org','worldbank.org'],url:'https://www.afdb.org/en/about-us/corporate-procurement/procurement-notices/current-solicitations',official:true},
 {id:'bilateral',name:'Development partners',domains:['giz.de','developpp.de'],url:'https://www.developpp.de/en/',official:true},
 {id:'innovation',name:'Innovation & technology',domains:['unicefventurefund.org','gsma.com','gcgh.grandchallenges.org'],url:'https://www.unicefventurefund.org/apply-funding',official:true},
 {id:'climate',name:'Climate & conservation',domains:['iucn.org','greenclimate.fund','thegef.org'],url:'https://iucn.org/procurement/currently-running-tenders',official:true},
 {id:'discovery',name:'Secondary discovery',domains:['opportunitydesk.org','fundsforngos.org','opportunitiesforafricans.com'],url:'https://opportunitydesk.org/',official:false}
];
const CAPABILITIES=[['Technical consulting & innovation',/\b(consultanc\w*|capacity building|entrepreneur\w*|startup\w*|start-up|innovation|renewable energy|water resources|climate|conservation|biodiversity|digital transformation)\b/i],['Drone operations',/\b(drone|uav|uas|rpas|lidar|photogrammetry)\b/i],['Geospatial services',/\b(gis|geospatial|mapping|remote sensing|earth observation|topographic|surveying)\b/i],['Agriculture',/\b(agricultur\w*|precision farming)\b/i],['Infrastructure & environment',/\b(inspection|environmental monitoring|disaster risk|climate adaptation|climate resilience|digital twin)\b/i],['Training & STEM',/\b(drone training|pilot training|stem education|technology education|digital skills|robotics|technology innovation|science education)\b/i]];
const opportunity=/\b(tender|rfp|rfq|procurement|bid|grant|funding|call for proposals|expression of interest|contract|partnership|consortium|accelerator|challenge|call for applications|applications open|apply now)\b/i;
export function canonical(value){try{const u=new URL(decode(value));if(u.protocol!=='https:'||u.username||u.password||u.port)return '';u.hash='';for(const k of [...u.searchParams.keys()])if(/^(utm_|fbclid|gclid|msclkid)/i.test(k))u.searchParams.delete(k);u.searchParams.sort();return u.href.replace(/\/$/,'');}catch{return '';}}
export function allowed(value){const u=canonical(value);if(!u)return false;const h=new URL(u).hostname;return SOURCES.some(s=>s.domains.some(d=>h===d||h.endsWith('.'+d)))||h==='www.bing.com';}
export function decode(s=''){return String(s).replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&#(\d+);/g,(_,n)=>{const v=Number(n);return v>0&&v<=0x10ffff?String.fromCodePoint(v):'';});}
export function plain(s=''){return decode(s.replace(/<(nav|header|footer)\b[^>]*>[\s\S]*?<\/\1>/gi,' ').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ')).replace(/\s+/g,' ').trim();}
function tag(s,t){return plain((s.match(new RegExp('<'+t+'\\b[^>]*>([\\s\\S]*?)</'+t+'>','i'))||[])[1]?.replace(/<!\[CDATA\[|\]\]>/g,'')||'');}
export function parseFeed(xml){if(!/<(?:rss|feed)\b/i.test(xml))throw Error('Source did not return an RSS/Atom feed');return (xml.match(/<(item|entry)\b[\s\S]*?<\/\1>/gi)||[]).slice(0,60).map(b=>({title:tag(b,'title'),excerpt:tag(b,'description')||tag(b,'summary')||tag(b,'content'),url:canonical(tag(b,'link')||b.match(/<link[^>]+href=["']([^"']+)/i)?.[1]||'')})).filter(x=>x.title&&x.url);}
export function feedURL(s){const slot=Math.floor(Date.now()/43200000),domain=s.domains[slot%s.domains.length];const region=slot%2?'Africa':'Malawi';const q=`${region} (tender OR grant OR partnership) (drone OR mapping OR agriculture OR training) site:${domain}`;return 'https://www.bing.com/search?format=rss&q='+encodeURIComponent(q);}
export function parsePPDA(html){const rows=(html.match(/<tr\b[\s\S]*?<\/tr>/gi)||[]);const results=[];for(const row of rows){const link=row.match(/href=["']([^"']*\/opentenders\/[^"']+)["']/i)?.[1];if(!link)continue;const cells=(row.match(/<td\b[\s\S]*?<\/td>/gi)||[]).map(plain);results.push({title:'Tender: '+(cells.find(x=>x.length>12&&!/view|download/i.test(x))||plain(row).slice(0,240)),scope:cells[0],organisation:cells[1]||'Not stated',excerpt:'Malawi procurement notice. '+plain(row)+(cells[4]&&/^\d{4}-\d{2}-\d{2}$/.test(cells[4])?' Closing date: '+cells[4]:''),url:canonical(new URL(decode(link),'https://www.ppda.mw/tenders').href)});}if(!results.length&&!/no tenders|no records|no data available/i.test(html))throw Error('PPDA layout needs manual review');return results.filter(x=>x.url).slice(0,100);}
export function deadline(text){
 const clean=text.replace(/(\d)(st|nd|rd|th)\b/gi,'$1');const m=clean.match(/(?:deadline(?: on)?|closing date|closes|submit(?:ted)? by)\s*[:\-]?\s*(\d{4}-\d{2}-\d{2}|\d{1,2}[ -][A-Za-z]{3,9}[ -]\d{4}|[A-Za-z]{3,9}\s+\d{1,2},?\s+\d{4})(.{0,55})/i);
 if(!m)return {date:null,label:/\b(rolling applications|rolling deadline|applications accepted on a rolling basis)\b/i.test(text)?'Rolling':'Not stated',timezone:'Not stated',evidence:''};
 const d=new Date(m[1]);const date=Number.isFinite(d.getTime())?d.toISOString().slice(0,10):null;return {date,label:date||'Not stated',timezone:m[2]?.match(/\b(?:UTC|GMT|CAT|EAT|CET|CEST)(?:\s*[+-]\s*\d{1,2}(?::\d{2})?)?\b/i)?.[0]||'Not stated',evidence:m[0].trim()};
}
export function assess(item,page='',source){const text=item.title+' '+(item.excerpt||'')+' '+page;const caps=CAPABILITIES.filter(([,r])=>r.test(text)).map(([n])=>n);if(!caps.length||!opportunity.test(text))return null;
 const geography=/\bmalawi\b/i.test(text)?'Malawi':/\b(southern africa|sadc)\b/i.test(text)?'Southern Africa':/\b(africa|african|sub-saharan)\b/i.test(text)?'Africa':/\b(global|worldwide|international bidders|developing countries)\b/i.test(text)?'International':'Not stated';
 const d=deadline((item.excerpt||'')+' '+page);const restriction=/\b(ngos? only|nonprofits? only|students? only|individuals? only|universities only|nationals only)\b/i.test(text);const partner=/\b(consortium|subcontractor|implementing partner|delivery partner)\b/i.test(text);
 const type=/\b(partnership|consortium|subcontractor)\b/i.test(item.title)?'Partnership':/\b(contract award|contract opportunity)\b/i.test(item.title)?'Contract':/\b(tender|rfp|rfq|procurement|bid|expression of interest)\b/i.test(text)?'Tender / RFQ':'Grant';
 const score=Math.min(95,35+caps.length*9+({Malawi:25,'Southern Africa':18,Africa:12,International:8}[geography]||0));
 const titleYear=Number(item.title.match(/\b(20\d{2})\b/)?.[1]||0);const historical=!d.date&&titleYear>0&&titleYear<new Date().getUTCFullYear()-1;
 return {historical,type,geography,score,deadline:d.date,deadlineLabel:d.label,timezone:d.timezone,deadlineEvidence:d.evidence,capabilities:caps,
 eligibility:'Needs review',routeHint:restriction?'Restrictions detected — check eligibility':partner?'Potential partner route — verify conditions':'Check applicant eligibility',
 reason:`Matches ${caps.join(', ')}. ${geography==='Not stated'?'Geography needs confirmation.':geography+' is mentioned in the notice.'} This is a relevance ranking, not confirmation that CAGE qualifies.`,
 organisation:item.organisation||'Not stated',estimatedValue:'Not stated',sourceKind:source?.official?'Official domain':'Secondary source',verification:page?'Page retrieved — staff verification required':'Search excerpt only',summary:plain(page||item.excerpt||'').slice(0,1200),requirements:[],checkedAt:new Date().toISOString()};}
export async function safeText(url,fetcher=fetch){if(!allowed(url))throw Error('Source domain requires manual review');let current=url;for(let n=0;n<4;n++){const r=await fetcher(current,{redirect:'manual',headers:{'User-Agent':'CAGE-Opportunity-Monitor/4.0'},signal:AbortSignal.timeout(6500)});if(r.status>=300&&r.status<400){current=new URL(r.headers.get('location')||'',current).href;if(!allowed(current))throw Error('Redirect requires manual review');continue;}if(!r.ok)throw Error('Source returned HTTP '+r.status);if(!/text|xml|json/i.test(r.headers.get('content-type')||''))throw Error('PDF or unsupported content — open the source manually');const reader=r.body?.getReader();if(!reader)throw Error('Empty source response');let size=0,parts=[];try{for(;;){const x=await reader.read();if(x.done)break;size+=x.value.length;if(size>1500000)throw Error('Source exceeds scan size limit');parts.push(x.value);}}finally{await reader.cancel().catch(()=>{});}const bytes=new Uint8Array(size);let off=0;for(const b of parts){bytes.set(b,off);off+=b.length;}return new TextDecoder().decode(bytes);}throw Error('Too many redirects');}
export const hash=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');

export function parseListing(html,source){if(source.id==='malawi')return parsePPDA(html);const out=[];const blocks=source.id==='innovation'?[html]:(html.match(/<tr\b[\s\S]*?<\/tr>/gi)||[]);for(const block of blocks){for(const m of block.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){let href;try{href=canonical(new URL(decode(m[1]),source.url).href);}catch{continue;}const title=plain(m[2]);if(!href||title.length<8)continue;const valid=source.id==='innovation'?new URL(href).pathname.startsWith('/call/'):source.id==='un'?/\/Public\/Notice\/\d+/i.test(href):source.id==='banks'?/\/documents?\/|\.pdf(?:\?|$)/i.test(href):/\/sites\/default\/files\//.test(href);if(!valid)continue;out.push({title:(source.id==='innovation'?'Funding call: ':'Tender: ')+title,scope:source.id==='innovation'?title:plain(block),excerpt:source.id==='innovation'?title:plain(block),url:href,organisation:({banks:'African Development Bank',innovation:'UNICEF Venture Fund',climate:'IUCN'}[source.id]||'Not stated')});}}if(!out.length&&!/no results|no tenders|no current|no records|no open/i.test(html))throw Error('Listing requires manual review or a newer portal');return out.slice(0,70);}

// Multiple independent discovery routes; search snippets are never treated as verified notices.
export function feedURLs(source){
 const slot=Math.floor(Date.now()/43200000);
 const terms=['(drone OR geospatial OR mapping OR surveying)','(agriculture OR climate OR innovation OR digital skills)'];
 return terms.map((term,i)=>'https://www.bing.com/search?format=rss&q='+encodeURIComponent(`(Malawi OR Africa OR global) (tender OR grant OR funding OR proposals) ${term} site:${source.domains[(slot+i)%source.domains.length]}`));
}
export function directFeeds(source){return source.id==='discovery'?['https://opportunitydesk.org/feed/','https://www.opportunitiesforafricans.com/feed/']:[];}
export function candidates(items,oldRows,saved,limit=40,rotation=Math.floor(Date.now()/60000)){
 const seen=new Set();const last=new Map(oldRows.map(x=>[canonical(x.source_url),x.raw_data?.checkedAt||'']));
 const ranked=items.filter(i=>allowed(i.url)).sort((a,b)=>{
  const aOld=last.get(a.url),bOld=last.get(b.url);
  if(!!aOld!==!!bOld)return aOld?1:-1;
  if(aOld&&bOld)return aOld.localeCompare(bOld);
  return (assess(b,'',b.source)?.score||0)-(assess(a,'',a.source)?.score||0);
 });
 const top=ranked.slice(0,Math.ceil((limit-saved.length)/2));const remaining=ranked.slice(top.length);const offset=remaining.length?rotation%remaining.length:0;
 return [...saved,...top,...remaining.slice(offset),...remaining.slice(0,offset)].filter(i=>{if(!i.url||seen.has(i.url))return false;seen.add(i.url);return true;}).slice(0,limit);
}
