import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {chromium} from 'playwright';
const root=fileURLToPath(new URL('../dist/',import.meta.url));
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local');let f=path.join(root,url.pathname==='/'?'apply.html':url.pathname);try{let body=fs.readFileSync(f);if(f.endsWith('/index.html'))body=body.toString().replace(/<script[\s\S]*?<\/script>/g,'');res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':f.endsWith('.png')?'image/png':'application/octet-stream');res.end(body);}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({executablePath:process.env.CAGE_TEST_CHROMIUM||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote']});const errors=[];
try{
const p=await browser.newPage({viewport:{width:390,height:844}});p.on('pageerror',e=>errors.push(e.message));
await p.route('**/runtime-config.js',r=>r.fulfill({contentType:'application/javascript',body:`window.CAGE_CONFIG={supabaseUrl:'${base}',supabaseAnonKey:'test'};`}));
await p.route('**/functions/v1/academy-admissions?*',async r=>{const action=new URL(r.request().url()).searchParams.get('action');const fields=[{id:'full_name',type:'text',label:'Name',required:true},{id:'email',type:'email',label:'Email',required:true},{id:'phone',type:'tel',label:'Phone',required:true}];const intake={id:'10000000-0000-4000-8000-000000000001',category:'RPL',title:'Test course',description:'Test',accepting:true,fields,fee:100,currency:'MWK',schedule:[],revision:1};let body=action==='catalog'?{intakes:[intake]}:action==='status'?{id:intake.id,status:'Accepted',fee:100,currency:'MWK',intake,files:[],balance:{fee:100,verified_paid:40,balance:60,due_on:'2026-10-01'}}:{ok:true};await r.fulfill({contentType:'application/json',body:JSON.stringify(body)});});
await p.addInitScript(()=>Object.defineProperty(crypto,'randomUUID',{value:undefined}));await p.goto(base);await p.locator('[data-apply-call]').click();
assert(await p.evaluate(()=>document.getElementById('application-form').compareDocumentPosition(document.getElementById('course-timetable'))&Node.DOCUMENT_POSITION_FOLLOWING));
await p.locator('[data-jump-timetable]').click();assert.equal(await p.evaluate(()=>document.activeElement.tagName),'SUMMARY');await p.locator('[data-jump-application]').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'application-heading');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await p.goto(base+'/#application=10000000-0000-4000-8000-000000000001&key='+'a'.repeat(64));await p.waitForSelector('#balance-date-form');assert((await p.locator('.cage-academy-balance-summary').innerText()).includes('60'));await p.locator('#balance-date-form [name=balance_due_on]').fill('2026-10-10');await p.locator('#balance-date-form button').click();await p.waitForSelector('#payment-proof-form');
console.log('PASS browser: application first, timetable below, both navigation links, mobile width, private-return balance/date form, older UUID API support.');
const staff=await browser.newPage({viewport:{width:1440,height:950}});staff.on('pageerror',e=>errors.push(e.message));
async function boot(){await staff.evaluate(()=>{window.CAGE_BACKEND={currentProfile:()=>({id:'u1',email:'alexander@cagemw.com',full_name:'Alexander',role:'admin'}),moduleLevel:()=> 'edit',isProduction:()=>false,scheduleSave:()=>{},boot:()=>{},canApprove:()=>true,opportunityData:async()=>[{id:'live-one',title:'New live tender',organization:'Test source',source_url:'https://example.test/opportunity',match_score:88,match_reason:'Test',status:'New',raw_data:{},found_at:new Date().toISOString()}]};});for(const f of ['app.js','refresh-recovery.js'])await staff.addScriptTag({path:path.join(root,f)});const emailSource=fs.readFileSync(path.join(root,'staff-email.js'),'utf8');const emailHandler=emailSource.slice(emailSource.indexOf('async function openEmailLink()'),emailSource.indexOf('// A separate explicit request'));await staff.addScriptTag({content:'const api=()=>window.CAGE_BACKEND;'+emailHandler});await staff.evaluate(()=>{window.dispatchEvent(new Event('cage:session-ready'));});
const restoring=await staff.evaluate(()=>document.body.classList.contains('restoring-workspace'));
if(restoring){await staff.waitForTimeout(150);assert.equal(await staff.locator('.app-shell').evaluate(el=>getComputedStyle(el).visibility),'hidden','default page must not flash before workspace readiness');}
await staff.evaluate(()=>openEmailLink());await staff.evaluate(()=>{document.getElementById('auth-gate').style.display='none';document.body.classList.remove('session-checking','auth-pending');window.dispatchEvent(new Event('cage:workspace-ready'));});await staff.waitForTimeout(800);assert.equal(await staff.evaluate(()=>document.body.classList.contains('restoring-workspace')),false,'loader must clear after recovery');}
await staff.goto(base+'/index.html');await boot();
const requestId=await staff.evaluate(()=>state.requests[0].id);
// Reproduce a saved My Work page with an old request URL still in the address bar.
await staff.evaluate(id=>{history.replaceState(null,'','?view=requests&record='+id);setView('mywork');},requestId);await staff.waitForTimeout(250);
await staff.reload();await boot();assert.equal(await staff.evaluate(()=>activeView),'mywork');assert.equal(await staff.locator('dialog[open]').count(),0,'old email link must not reopen a closed request');
// A genuinely different incoming link still wins over a saved page.
await staff.goto(base+'/index.html?view=requests&record='+requestId+'&source=new-email#keep');await boot();assert.equal(await staff.evaluate(()=>activeView),'requests');assert(await staff.locator('#request-detail-dialog').isVisible());assert.equal(new URL(staff.url()).searchParams.get('record'),null);assert.equal(new URL(staff.url()).searchParams.get('source'),'new-email');assert.equal(new URL(staff.url()).hash,'#keep');
// An open request stays open on refresh, but closing it and leaving prevents replay.
await staff.waitForTimeout(250);await staff.reload();await boot();assert(await staff.locator('#request-detail-dialog').isVisible());
await staff.evaluate(()=>{document.getElementById('request-detail-dialog').close();setView('mywork');});await staff.waitForTimeout(250);await staff.reload();await boot();assert.equal(await staff.evaluate(()=>activeView),'mywork');assert.equal(await staff.locator('dialog[open]').count(),0);
console.log('PASS real email-link handler + recovery: stale request URL/My Work, new email link precedence, query/hash preservation, open request recovery, closed request stays closed after navigation.');
assert.equal(errors.length,0,errors.join('\n'));
}finally{await browser.close();server.close();}
